drop policy "Enable insert for authenticated users only" on "public"."Products";

drop policy "Enable read access for authenticated users" on "public"."Products";

create table "public"."Locations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "storage_bin" text not null
);


alter table "public"."Locations" enable row level security;

CREATE UNIQUE INDEX "Locations_pkey" ON public."Locations" USING btree (id);

alter table "public"."Locations" add constraint "Locations_pkey" PRIMARY KEY using index "Locations_pkey";

create policy "Acceso al CRUD completo para todos los usuarios autenticados"
on "public"."Locations"
as permissive
for all
to authenticated
using (true)
with check (true);


create policy "Acceso al CRUD completo para todos los usuarios autenticados"
on "public"."Products"
as permissive
for all
to authenticated
using (true)
with check (true);



