create table "public"."Inventories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "closed_at" timestamp with time zone,
    "name" text not null
);


alter table "public"."Inventories" enable row level security;

create table "public"."InventoryItems" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "location_id" bigint not null,
    "barcode" text,
    "product_id" bigint not null,
    "quantity" numeric not null,
    "observations" text,
    "inventory_id" bigint not null
);


alter table "public"."InventoryItems" enable row level security;

CREATE UNIQUE INDEX "Inventories_pkey" ON public."InventoryItems" USING btree (id);

CREATE UNIQUE INDEX "Inventories_pkey1" ON public."Inventories" USING btree (id);

alter table "public"."Inventories" add constraint "Inventories_pkey1" PRIMARY KEY using index "Inventories_pkey1";

alter table "public"."InventoryItems" add constraint "Inventories_pkey" PRIMARY KEY using index "Inventories_pkey";

alter table "public"."InventoryItems" add constraint "InventoryItems_inventory_id_fkey" FOREIGN KEY (inventory_id) REFERENCES "Inventories"(id) ON UPDATE CASCADE not valid;

alter table "public"."InventoryItems" validate constraint "InventoryItems_inventory_id_fkey";

alter table "public"."InventoryItems" add constraint "InventoryItems_location_id_fkey" FOREIGN KEY (location_id) REFERENCES "Locations"(id) ON UPDATE CASCADE not valid;

alter table "public"."InventoryItems" validate constraint "InventoryItems_location_id_fkey";

alter table "public"."InventoryItems" add constraint "InventoryItems_product_id_fkey" FOREIGN KEY (product_id) REFERENCES "Products"(id) ON UPDATE CASCADE not valid;

alter table "public"."InventoryItems" validate constraint "InventoryItems_product_id_fkey";


